services:
  lab-postgres:
    image: ankane/pgvector
    container_name: lab-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: lab
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - lab-postgres:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  lab-ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: lab-ollama
    ports:
      - "11434:11434"
    volumes:
      - lab-ollama:/root/.ollama

  lab-rabbitmq:
    image: rabbitmq
    container_name: lab-rabbitmq
    ports:
      - "5672:5672"

volumes:
  lab-postgres:
  lab-ollama: