services:
  lab-postgres:
    image: ankane/pgvector
    container_name: lab-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - lab-postgres:/var/lib/postgresql/data
    networks:
        - 001-network

  lab-ollama:
    image: ollama/ollama
    container_name: lab-ollama
    ports:
      - "11434:11434"
    volumes:
      - lab-ollama:/root/.ollama
    runtime: nvidia
    networks:
        - 001-network

  lab-rabbitmq:
    image: rabbitmq
    container_name: lab-rabbitmq
    ports:
      - "5672:5672"
    networks:
        - 001-network

networks:
  001-network:
    external: true
    
volumes:
  lab-postgres:
  lab-ollama: