services:
  lab-postgres:
    image: ankane/pgvector
    container_name: lab-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: lab
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - lab-postgres:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
        - network_001

  lab-ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: lab-ollama
    runtime: nvidia
    ports:
      - "11434:11434"
    volumes:
      - lab-ollama-config:/root/.ollama
      - lab-ollama-models:/models
      - lab-ollama-logs:/var/log/ollama
    environment:
      - OLLAMA_DEBUG=false
      - OLLAMA_KEEP_ALIVE=-1
    networks:
      - network_001

  lab-rabbitmq:
    image: rabbitmq
    container_name: lab-rabbitmq
    ports:
      - "5672:5672"
    networks:
        - network_001
  

networks:
  network_001:
    external: true
    
volumes:
  lab-postgres:
  lab-ollama-logs:
  lab-ollama-config:
  lab-ollama-models:
