services:
  db-lab:
    image: ankane/pgvector
    container_name: db-lab
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - db-lab:/var/lib/postgresql/data
    networks:
        - 001-network

  ollama:
    image: ollama/ollama
    container_name: ollama-lab
    ports:
      - "11434:11434"
    volumes:
      - ollama-lab:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    networks:
        - 001-network

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq-lab
    ports:
      - "5672:5672"
    networks:
        - 001-network
  

networks:
  001-network:
    external: true
    
volumes:
  db-lab:
  ollama-lab: